# Generated by Django 3.2.25 on 2026-09-16 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('calibration_organization', models.CharField(max_length=200)),
                ('result', models.CharField(choices=[('conforming', 'Conforming'), ('non_conforming', 'Non-Conforming')], max_length=30)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='calibration_certificates/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-calibration_date'],
            },
        ),
    ]
