# Generated by Django 3.2.25 on 2026-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibration',
            name='calibration_organization',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='result',
        ),
        migrations.AddField(
            model_name='calibration',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='calibration',
            name='next_calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='performed_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='calibration',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('failed', 'Failed')], default='scheduled', max_length=20),
        ),
    ]
