# Generated by Django 3.2.25 on 2026-09-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('building', models.CharField(blank=True, max_length=200)),
                ('room', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
