# Generated by Django 3.2.25 on 2026-09-16 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=150)),
                ('serial_number', models.CharField(max_length=150)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('out_of_service', 'Out of Service'), ('maintenance', 'In Maintenance')], default='in_service', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instruments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='suppliers.location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['internal_code'],
            },
        ),
    ]
